version: "2"
services:
  api:
    build: .
    ports:
    - 5000:5000
    depends_on:
    - mongo
    networks:
    - newport_network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    
networks:
  newport_network:
    driver: bridge
  