version: "2"
services:
  web:
    build: .
    ports:
    - 5000:5000
    depends_on:
    - mongo
    networks:
    - newport-network
networks:
  newport-network:
    driver: bridge
  mongo:
    image: mongo
    ports:
      - "27017:27017"