version: "2"
services:
  api:
    build: .
    ports:
    - 5000:5000
    depends_on:
    - mongo
    networks:
    - newport_network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    
networks:
  newport_network:
    driver: bridge
  